### ISSUE TITLE
Properly append scripts to baselayout scripts section

### ISSUE THREAD

**Issue by daniel-j-h** [blaringsilence/pegasus#13]
Currently your layout template contains a scripts section:

https://github.com/blaringsilence/pegasus/blob/c48fe1e5577116f0d88e2b51451afb05ebc05b69/pegasus/templates/layout.html#L98-L102

but your register template simply puts the script behind its form:

https://github.com/blaringsilence/pegasus/blob/c48fe1e5577116f0d88e2b51451afb05ebc05b69/pegasus/templates/register.html#L30-L106

The following allows you do do what you intended. In your layout, wrap everything script related in a Jinja2 block at the end of the document, let's name it "scripts":

``` python
{% block scripts %}
..
{% endblock scripts %}
```

In templates inheriting from layout (e.g. the register template) put scripts in a separate block (name it "scripts" here, too) and then call the `super()` function.

``` python
{% block scripts %}
{{ super() }}
...
{% endblock scripts %}
```

This makes sure you first get all the scripts from the layout template at the end of of your document, and then you get the scripts from the register template appended.

(By the way, you can do the same for other logical sections in your layout html when it could make sense for a inheriting template to customize or append something to it, e.g. a css block in case only specific templates need some css)

**Comment by mariamrf** [comment]
1 change: since I'll always need any scripts from layout.html to load first (currently they're jquery, bootstrap.min.js, and a global variable) I opted for a scripts block beneath the layout.html scripts in the scripts section (that is the most I've used the word 'scripts' in a sentence..) so other templates will just overwrite this block without having to worry about forgetting to call super(). 
But it's useful to know that I _can_ call super().
